# Generated by Django 2.2.4 on 2019-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_photo_filepath',
            new_name='photo_filename',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reset_password',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='reset_password'),
        ),
    ]
