# Generated by Django 2.2.4 on 2019-09-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190829_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__username',), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
