# Generated by Django 2.2.4 on 2019-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190902_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang_key',
            field=models.CharField(choices=[('RO', 'RO'), ('EN', 'EN')], default='RO', max_length=50),
        ),
    ]
