# Generated by Django 2.2.4 on 2019-09-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190907_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('guest', 'guest')], default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
