# Generated by Django 2.2.4 on 2019-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190907_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_filename',
            field=models.CharField(blank=True, max_length=100, verbose_name='profile_photo'),
        ),
    ]
