# Generated by Django 2.2.3 on 2019-07-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_userfavorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='category',
            new_name='categories',
        ),
    ]
