# Generated by Django 2.2.3 on 2019-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190729_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='categories',
            field=models.ManyToManyField(blank=True, to='gallery.Category'),
        ),
    ]
