# Generated by Django 2.2.3 on 2019-07-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20190730_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gallery.Tag'),
        ),
    ]
