# Generated by Django 2.2.3 on 2019-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190731_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.CharField(default=0, max_length=100, verbose_name='thumbnail_path'),
            preserve_default=False,
        ),
    ]
