# Generated by Django 2.2.3 on 2019-08-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='categories',
            field=models.ManyToManyField(blank=True, to='gallery.Category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(verbose_name='creation_date'),
        ),
    ]
