# Generated by Django 2.2.3 on 2019-08-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20190803_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='file name')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'medias',
                'ordering': ('date', 'filename'),
                'permissions': (('view', 'Can see all medias'), ('scan', 'Can scan the medias directory')),
            },
        ),
        migrations.RemoveField(
            model_name='photoaccesspolicy',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='photoaccesspolicy',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photoaccesspolicy',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userfavorites',
            name='album',
        ),
        migrations.RemoveField(
            model_name='userfavorites',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='album',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.CharField(max_length=100, verbose_name='thumbnail_name'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='AlbumAccessPolicy',
        ),
        migrations.DeleteModel(
            name='PhotoAccessPolicy',
        ),
        migrations.DeleteModel(
            name='UserFavorites',
        ),
        migrations.AddField(
            model_name='media',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
        migrations.AddField(
            model_name='albumtag',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
        migrations.AddField(
            model_name='albumtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Tag'),
        ),
        migrations.AddField(
            model_name='albumcategory',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album'),
        ),
        migrations.AddField(
            model_name='albumcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AddField(
            model_name='photo',
            name='media_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallery.Media'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together={('album', 'filename')},
        ),
    ]
