# Generated by Django 2.2.4 on 2019-08-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_album_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'default_permissions': ('view',), 'ordering': ('date', 'filename'), 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
