# Generated by Django 2.2.3 on 2019-08-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20190803_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ('date', 'filename'), 'verbose_name': 'media', 'verbose_name_plural': 'medias'},
        ),
    ]
