# Generated by Django 2.2.3 on 2019-08-03 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20190803_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('date', 'name', 'dirpath'), 'permissions': (('add_permissions', 'Add permissions'), ('change_permissions', 'Change permissions'), ('delete_permissions', 'Delete permissions')), 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
