# Generated by Django 2.2.4 on 2019-08-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
