# Generated by Django 2.2.3 on 2019-08-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20190803_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('date', 'name', 'dirpath'), 'permissions': (('add_photos', 'Add photos'), ('add_permissions', 'Add permissions'), ('change_permissions', 'Change permissions'), ('delete_permissions', 'Delete permissions')), 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
    ]
