# Generated by Django 2.2.4 on 2019-08-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_favoritealbum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowAlbum',
        ),
    ]
