# Generated by Django 2.2.3 on 2019-08-12 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=200, verbose_name='directory path')),
                ('date', models.DateField(verbose_name='creation_date')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ('date', 'name', 'folder_path'),
                'permissions': (('add_photos', 'Add photos'), ('add_permissions', 'Add permissions'), ('change_permissions', 'Change permissions'), ('delete_permissions', 'Delete permissions')),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'unique_together': {('folder_path',)},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Album')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Album')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='file name')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Album')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ('date', 'filename'),
                'default_permissions': ('add', 'view', 'change', 'delete'),
                'unique_together': {('album', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='file name')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thumbnail_file', models.CharField(max_length=100, verbose_name='thumbnail_name')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Album')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ('date', 'filename'),
                'default_permissions': ('add', 'view', 'change', 'delete'),
                'unique_together': {('album', 'filename')},
            },
        ),
    ]
