# Generated by Django 2.2.3 on 2019-08-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_albumuserfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcategory',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Album'),
        ),
        migrations.AlterField(
            model_name='albumcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.gallery.Category'),
        ),
    ]
