# Generated by Django 2.2.3 on 2019-08-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190812_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('date', 'name', 'folder_path'), 'permissions': (('add_permissions', 'Add permissions'), ('change_permissions', 'Change permissions'), ('delete_permissions', 'Delete permissions'), ('add_photos', 'Add photos'), ('change_photos', 'Change photos'), ('delete_photos', 'Delete photos')), 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
    ]
