# Generated by Django 2.2.4 on 2019-08-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumUserFavorites',
        ),
    ]
