# Generated by Django 2.2.4 on 2019-08-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_followalbum_followuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followalbum',
            name='album',
        ),
        migrations.RemoveField(
            model_name='followalbum',
            name='user',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='FollowAlbum',
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
