# Generated by Django 2.2.4 on 2019-08-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20190826_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='favorites',
        ),
    ]
