# Generated by Django 2.2.4 on 2019-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_album_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('date', 'name'), 'permissions': (('add_permissions', 'Add permissions'), ('change_permissions', 'Change permissions'), ('delete_permissions', 'Delete permissions'), ('add_photos', 'Add photos'), ('change_photos', 'Change photos'), ('delete_photos', 'Delete photos')), 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='creation_date'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='album',
            name='folder_path',
        ),
    ]
