# Generated by Django 2.2.4 on 2019-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='log date'),
        ),
    ]
