# Generated by Django 2.2.4 on 2019-09-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20190918_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionlog',
            old_name='action',
            new_name='operation',
        ),
    ]
