# Generated by Django 2.2.4 on 2019-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20190918_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='operation',
            field=models.CharField(choices=[('ADD', 'add'), ('DELETE', 'delete'), ('MODIFY', 'modify')], default='ADD', max_length=15),
        ),
    ]
