# Generated by Django 2.2.4 on 2019-09-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_auto_20190920_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='log date'),
        ),
    ]
